// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxpwracjakqpqpoivypm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4cHdyYWNqYWtxcHFwb2l2eXBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTMzMzIsImV4cCI6MjA3Mzg2OTMzMn0.O7LHvEsfyFQT0FwYqyk9AKZ_mmIBaxgiTS1S5Utkk6c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});